@startuml st02-login-mfa
actor User
participant "AuthController" as AC
participant "RiskEngine" as RK
participant "MFA Service" as MFA
participant "LoginEventStore" as ES

User -> AC : POST /login
AC -> RK : evaluate risk
RK --> AC : riskLevel = MEDIUM/HIGH
AC -> MFA : createChallenge(userId)
MFA --> User : Gửi OTP / push notification
User -> AC : POST /mfa/verify {otp}
AC -> MFA : verify(challengeId, otp)
MFA --> AC : PASS
AC -> ES : create Session
AC --> User : 200 OK + token
@enduml